= My Project
Lukas Lummerstorfer
1.0.0, 2021-10-20: 3BHITM
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektantrag Lukas Lummerstorfer


== Idee:

Ich möchte ein Projekt machen, welches ein Stromabrechnungssystem simulieren soll.
Das ganze soll über eine grafische Nutzeroberfläche gesteuert werden können.

== Technologien die ich verwende:

	•	Java
	•	Java FX
	•	Maven

== Funktionalitäten:

Der Benutzer soll in einer grafischen Nutzeroberfläche seine ID bzw. seinen Namen eingeben können. In einem weiteren
Feld sollen die verbrauchten kWh eingetragen werden. Drückt mann dann auf berechnen, sollte ein Fenster erscheinen, dass eine Stromabrechnung darstellet.
Zudem sollte es noch einen Button für Print geben. Dieser soll die Rechnung bei bedarf ausdrucken.

== Motivation

Ich möchte mit diesem Projekt erstmals grafisches Programmieren mit Java ausprobieren.